package mx.edumat.modati.servicios.modelo;
// Generated 18/05/2015 06:41:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contexto generated by hbm2java
 */
public class Contexto  implements java.io.Serializable {


     private Integer id;
     private String desc;
     private Set registros = new HashSet(0);

    public Contexto() {
    }

	
    public Contexto(String desc) {
        this.desc = desc;
    }
    public Contexto(String desc, Set registros) {
       this.desc = desc;
       this.registros = registros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


