package mx.edumat.modati.servicios.modelo;
// Generated 18/05/2015 06:41:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private Integer id;
     private String descUrl;
     private Set registros = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(String descUrl) {
        this.descUrl = descUrl;
    }
    public Recurso(String descUrl, Set registros, Set usuarios) {
       this.descUrl = descUrl;
       this.registros = registros;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescUrl() {
        return this.descUrl;
    }
    
    public void setDescUrl(String descUrl) {
        this.descUrl = descUrl;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


