package mx.edumat.modati.servicios.modelo;
// Generated 18/05/2015 06:41:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String user;
     private String pass;
     private Set registros = new HashSet(0);
     private Set recursos = new HashSet(0);
     private Set busquedas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String user, String pass) {
        this.user = user;
        this.pass = pass;
    }
    public Usuario(String user, String pass, Set registros, Set recursos, Set busquedas) {
       this.user = user;
       this.pass = pass;
       this.registros = registros;
       this.recursos = recursos;
       this.busquedas = busquedas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }
    public Set getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(Set recursos) {
        this.recursos = recursos;
    }
    public Set getBusquedas() {
        return this.busquedas;
    }
    
    public void setBusquedas(Set busquedas) {
        this.busquedas = busquedas;
    }




}


