package iing.uabc.edu.mx.persistencia.modelo;
// Generated 18/05/2015 06:41:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Busqueda generated by hbm2java
 */
public class Busqueda  implements java.io.Serializable {


     private Integer id;
     private String descTermino;
     private Set<Registro> registros = new HashSet(0);
     private Set<Usuario> usuarios = new HashSet(0);

    public Busqueda() {
    }

	
    public Busqueda(String descTermino) {
        this.descTermino = descTermino;
    }
    
    public Busqueda(String descTermino, Set<Registro> registros, Set<Usuario> usuarios) {
       this.descTermino = descTermino;
       this.registros = registros;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescTermino() {
        return this.descTermino;
    }
    
    public void setDescTermino(String descTermino) {
        this.descTermino = descTermino;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


