package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Busqueda generated by hbm2java
 */
public class Busqueda  implements java.io.Serializable {


     private Integer id;
     private String descTermino;
     private Set registroBusquedas = new HashSet(0);
     private Set usuarioBusquedas = new HashSet(0);

    public Busqueda() {
    }

	
    public Busqueda(String descTermino) {
        this.descTermino = descTermino;
    }
    public Busqueda(String descTermino, Set registroBusquedas, Set usuarioBusquedas) {
       this.descTermino = descTermino;
       this.registroBusquedas = registroBusquedas;
       this.usuarioBusquedas = usuarioBusquedas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescTermino() {
        return this.descTermino;
    }
    
    public void setDescTermino(String descTermino) {
        this.descTermino = descTermino;
    }
    public Set getRegistroBusquedas() {
        return this.registroBusquedas;
    }
    
    public void setRegistroBusquedas(Set registroBusquedas) {
        this.registroBusquedas = registroBusquedas;
    }
    public Set getUsuarioBusquedas() {
        return this.usuarioBusquedas;
    }
    
    public void setUsuarioBusquedas(Set usuarioBusquedas) {
        this.usuarioBusquedas = usuarioBusquedas;
    }




}


