package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proceso generated by hbm2java
 */
public class Proceso  implements java.io.Serializable {


     private Integer id;
     private String desc;
     private Set registros = new HashSet(0);

    public Proceso() {
    }

	
    public Proceso(String desc) {
        this.desc = desc;
    }
    public Proceso(String desc, Set registros) {
       this.desc = desc;
       this.registros = registros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


