package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1


import java.util.Objects;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private Integer id;
     private String descUrl;

    public Recurso() {
    }
	
    public Recurso(String descUrl) {
        this.descUrl = descUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescUrl() {
        return this.descUrl;
    }
    
    public void setDescUrl(String descUrl) {
        this.descUrl = descUrl;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.id);
        hash = 79 * hash + Objects.hashCode(this.descUrl);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Recurso other = (Recurso) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return Objects.equals(this.descUrl, other.descUrl);
    }
}