package iing.uabc.edu.mx.persistencia.modelo;

import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private Integer id;
     private String descUrl;
     private Set<Registro> registros = new HashSet(0);
     private Set<Usuario> usuarios = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(String descUrl) {
        this.descUrl = descUrl;
    }

    public Recurso(String descUrl, Set<Registro> registros, Set<Usuario> usuarios) {
       this.descUrl = descUrl;
       this.registros = registros;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescUrl() {
        return this.descUrl;
    }
    
    public void setDescUrl(String descUrl) {
        this.descUrl = descUrl;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }

    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

}


