package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1

import java.util.Objects;

/**
 * RegistroBusqueda generated by hbm2java
 */
public class RegistroBusqueda  implements java.io.Serializable {
     private int id;
     private Busqueda busqueda;
     private Registro registro;

    public RegistroBusqueda() {
    }

    public RegistroBusqueda(int id, Busqueda busqueda, Registro registro) {
       this.id = id;
       this.busqueda = busqueda;
       this.registro = registro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Busqueda getBusqueda() {
        return this.busqueda;
    }
    
    public void setBusqueda(Busqueda busqueda) {
        this.busqueda = busqueda;
    }
    public Registro getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Registro registro) {
        this.registro = registro;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + this.id;
        hash = 29 * hash + Objects.hashCode(this.busqueda);
        hash = 29 * hash + Objects.hashCode(this.registro);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RegistroBusqueda other = (RegistroBusqueda) obj;
        if (this.id != other.id) {
            return false;
        }
        if (!Objects.equals(this.busqueda, other.busqueda)) {
            return false;
        }
        return Objects.equals(this.registro, other.registro);
    }
}