package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1



/**
 * RegistroBusqueda generated by hbm2java
 */
public class RegistroBusqueda  implements java.io.Serializable {


     private int id;
     private Busqueda busqueda;
     private Registro registro;

    public RegistroBusqueda() {
    }

    public RegistroBusqueda(int id, Busqueda busqueda, Registro registro) {
       this.id = id;
       this.busqueda = busqueda;
       this.registro = registro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Busqueda getBusqueda() {
        return this.busqueda;
    }
    
    public void setBusqueda(Busqueda busqueda) {
        this.busqueda = busqueda;
    }
    public Registro getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Registro registro) {
        this.registro = registro;
    }




}


