package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1

import java.util.Objects;


/**
 * UsuarioBusqueda generated by hbm2java
 */
public class UsuarioBusqueda  implements java.io.Serializable {
     private int id;
     private Busqueda busqueda;
     private Usuario usuario;
     private int veces;
     
    public UsuarioBusqueda() {
    }

    public UsuarioBusqueda(int id, Busqueda busqueda, Usuario usuario) {
       this.id = id;
       this.busqueda = busqueda;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Busqueda getBusqueda() {
        return this.busqueda;
    }
    
    public void setBusqueda(Busqueda busqueda) {
        this.busqueda = busqueda;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public int getVeces() {
        return veces;
    }
    
    public void setVeces(int veces) {
        this.veces = veces;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + this.id;
        hash = 97 * hash + Objects.hashCode(this.busqueda);
        hash = 97 * hash + Objects.hashCode(this.usuario);
        hash = 97 * hash + this.veces;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UsuarioBusqueda other = (UsuarioBusqueda) obj;
        if (this.id != other.id) {
            return false;
        }
        if (!Objects.equals(this.busqueda, other.busqueda)) {
            return false;
        }
        if (!Objects.equals(this.usuario, other.usuario)) {
            return false;
        }
        return this.veces == other.veces;
    }

}