package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String user;
     private String pass;
     private Set registros = new HashSet(0);
     private Set usuarioRecursos = new HashSet(0);
     private Set usuarioBusquedas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String user, String pass) {
        this.user = user;
        this.pass = pass;
    }
    public Usuario(String user, String pass, Set registros, Set usuarioRecursos, Set usuarioBusquedas) {
       this.user = user;
       this.pass = pass;
       this.registros = registros;
       this.usuarioRecursos = usuarioRecursos;
       this.usuarioBusquedas = usuarioBusquedas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }
    public Set getUsuarioRecursos() {
        return this.usuarioRecursos;
    }
    
    public void setUsuarioRecursos(Set usuarioRecursos) {
        this.usuarioRecursos = usuarioRecursos;
    }
    public Set getUsuarioBusquedas() {
        return this.usuarioBusquedas;
    }
    
    public void setUsuarioBusquedas(Set usuarioBusquedas) {
        this.usuarioBusquedas = usuarioBusquedas;
    }




}


