package iing.uabc.edu.mx.persistencia.modelo;
// Generated Jun 8, 2015 9:23:00 PM by Hibernate Tools 4.3.1

import java.util.Objects;

/**
 * UsuarioRecurso generated by hbm2java
 */
public class UsuarioRecurso  implements java.io.Serializable {
     private int id;
     private Recurso recurso;
     private Usuario usuario;
     private int visitas;

    public UsuarioRecurso() {
    }

    public UsuarioRecurso(int id, Recurso recurso, Usuario usuario) {
       this.id = id;
       this.recurso = recurso;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public int getVisitas() {
        return visitas;
    }
    
    public void setVisitas(int visitas) {
        this.visitas = visitas;
    }
    
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 47 * hash + this.id;
        hash = 47 * hash + Objects.hashCode(this.recurso);
        hash = 47 * hash + Objects.hashCode(this.usuario);
        hash = 47 * hash + this.visitas;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UsuarioRecurso other = (UsuarioRecurso) obj;
        if (this.id != other.id) {
            return false;
        }
        if (!Objects.equals(this.recurso, other.recurso)) {
            return false;
        }
        if (!Objects.equals(this.usuario, other.usuario)) {
            return false;
        }
        if (this.visitas != other.visitas) {
            return false;
        }
        return true;
    }
}